resources:
- name: source-code
  type: git
  icon: github
  source:
    uri: https://github.com/PhilipJonasFranz/GraphvizOnline.git
    branch: master
    username: ((github_token))
    password: x-oauth-basic
    tag_filter: "*"

- name: jfrog-docker
  type: registry-image
  icon: docker
  source:
    repository: jfrog.tinycloud.space/docker/graphviz-online
    username: ((jfrog_user))
    password: ((jfrog_password))
    tag: latest

jobs:
- name: build-and-push
  plan:
  - get: source-code
    trigger: true
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: source-code
      outputs:
      - name: image
      params:
        CONTEXT: source-code/frontend
      run:
        path: build
  - put: jfrog-docker
    params:
      image: image/image.tar
      additional_tags: source-code/.git/ref